### ISSUE TITLE
Companion Class Interacts with Mature and Nimble Feats to produce incorrect values

### ISSUE THREAD

**Issue by Tevarrus** [TikaelSol/PF2e-Animal-Companions#10] opened 2021-07-13 17:32 UTC
In producing a Wolf Companion with both the Mature and Nimble feats I noticed that the Reflex and Will Saves were incorrectly set to Master instead of Expert, and Acrobatics was set to Master instead of Expert.

Applying the Animal Companion Class and the Mature Animal Companion feat each on their own produced correct Save values, however applying both simultaneously produced the error, and the same with the Animal Companion Class and the Nimble Companion Feat pertaining to Acrobatics, so I assumed an issue with the value and mode of the effects.

I was able to correct the Save values by editing the Animal Companion class JSON under "Effects" and changing the "Mode" and "Priority" values for Will and Reflex rank from (2, 2) to (4, 1), mimicking Fortitude rank which was behaving correctly as a baseline.

I was similarly able to correct the Acrobatics value by editing the Nimble Companion JSON under "Effects" and changing the Acrobatics "Value" to 1, the "Mode" to 2, and the Priority to "2", setting it to add instead.

Essentially "Mode 4" was setting a baseline to which other values were being added with "Mode 2" when it seems like it was intended to be a replacement value and they were stacking incorrectly as a result; hopefully this helps address the issues.

![Animal Companion Class JSON Effects Edit](https://user-images.githubusercontent.com/84486231/125498591-503625c7-8034-4efb-8de7-d3894965417f.png)

![Nimble Companion Feat JSON Effects Edit](https://user-images.githubusercontent.com/84486231/125514660-f24c238f-c00a-4dd0-bf80-0d0e1eeeb9dc.png)

(tested on Foundry 0.8.8 with no other mods active in a fresh test world)

**Comment by TikaelSol** [comment] 2021-07-13 17:42
This likely got broke while trying to fix a bug with Active Effects.  I'll go audit the values sometime this week when I have a moment and make sure everything is set up correctly.  Thanks for bringing it up!

**Comment by Tevarrus** [comment] 2021-07-13 19:43
> This likely got broke while trying to fix a bug with Active Effects. I'll go audit the values sometime this week when I have a moment and make sure everything is set up correctly. Thanks for bringing it up!

Ahhhh, makes sense. Found a similar issue with Nimble and Acrobatics and edited the post to include it.

Thanks for all your work!

**Comment by JonWaterfall** [comment] 2021-07-16 23:55
I see that this issue is being worked on. Nice!

I just wanna add that my player is also noticing that their wolf has a bit much AC, caused by the wolf becoming a master in unarmored defence, without the ability to reduce the proficiency through right-clicking.

**Comment by TikaelSol** [comment] 2021-07-17 00:00
Yes, this issue will be fixed (as well as several others) in the next release, but it requires a new system tool that we are still working on. Foundry's base active effect system changed too much to work well with the module.

**Comment by TikaelSol** [comment] 2021-07-18 07:01
We merged in the new Rule Element to PF2e dev version today and just fixed both this issue and the issue with proficiencies disappearing on reload of Foundry.  So this will be fixed soon, but I have to wait for the next public release of PF2e which will need some time for the dev build to be more stable.

**Comment by TikaelSol** [comment] 2021-07-23 00:14
Closed with the new release!

**Closed by TikaelSol** 2021-07-23 00:14 UTC
