### ISSUE TITLE
Barding

### ISSUE THREAD

**Issue by discostu24** [TikaelSol/PF2e-Animal-Companions#11] opened 2021-07-20 21:02 UTC
Thank you for your mod!

Could you add barding?  Or is it in here already?

I don't see a way to give animal companions Barding and make their AC accurate.

**Comment by TikaelSol** [comment] 2021-07-20 21:09
Give them a new light armor and give it the right stats.  There is no barding proficiency so we just have to latch onto one of the existing armor proficiencies.  Unfortunately the armor types are hard coded in the system, I tried adding in a new proficiency for them with the module but the system always interprets it as a weapon instead of armor.  I don't think this is going to change until the module gets absorbed into the core system (will happen when we get a dedicated sheet).  I could go change the system to accept barding as an armor proficiency but I'd need to find a new way to have that not show up on regular characters and would require I migrate all existing PCs .  I'll keep it in mind while I'm working on the system though and the next time we do a change to PC data structure maybe I'll try to sneak that in.

**Comment by TikaelSol** [comment] 2022-01-15 05:13
Closing, as the issue is not going to be in scope for the module.

**Closed by TikaelSol** 2022-01-15 05:13 UTC
