### ISSUE TITLE
Construct Companion Expert/Master/Legendary Overdrive 

### ISSUE THREAD

**Issue by ARandomGuy15** [TikaelSol/PF2e-Animal-Companions#34] opened 2022-05-13 10:52 UTC
The additional 1/2/3 from the Expert/Master/Legendary Overdrive class feature are not accounted for on a innovation construct companion.
Temporary fix implemented was moving over a copy of the relevant class feature from the inventor to the companion.

Compared to the intelligence score issue (solved in this case by manually adjusted Int on companion too match inventors) which makes itself apparent, this issue is more subtle and only becomes noticeable beginning at level 3.

**Comment by TikaelSol** [comment] 2022-09-18 02:57
I'm going to close this as `won't fix`. The issue is that this is something for the system itself to implement. There's no way to reference the abilities of the granting actor on an effect, and if I hard code in increases to overdrive then I get multiclass inventors wrong.

**Closed by TikaelSol** 2022-09-18 02:57 UTC
